name: Encode Keystore to Base64

on:
  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Encode keystore
        run: base64 -w 0 temp/release.keystore > release.keystore.base64.txt

      - name: Upload encoded file
        uses: actions/upload-artifact@v4
        with:
          name: encoded-keystore
          path: release.keystore.base64.txt
